appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: TZeWaMl42WlZFkyeYEIl4TplNHjQQJqqP/OoapD1Ng29ftZXJcn3RZTVFfx7pjGVEiPk5as0KEHtNEveUfiov1hXFCSz6SHmpv71lgU3WZt5LpnrLvV23DStFgApWkpC/pFHSCJka/snD1vc5wkqpXUqkGyIUaToI0iaAM9GA+iWOkvRO4VhRMyxqQLo1TNTdm9FWSCecabWTHJZ+JqGzZLM6iywQrRzkCrjtYI0BUdGD8msi9oe1uhs0kCwfDiw5w/dVG0OTlo6hKO9xNtU8mrom3kr8yvfz/WF2EmmurqlpJ2+81jkGR0sfnSj9LXrZ2doNKVdtOKlAkvLNwodjm5g0jXixYfAPRXwhxja7Hm5kfrLvx4Mrxo53T4B6mokQm03yrFjPrOIC8cZIO2Z/hgCDTS1lyAtSY2AmIi7yqqbZf+T8O2IJLerW86u8izkP+2MDpm+1WYkub5O//YVJJnec/Zqz8PzaOmN4cN/5M4QdL1fFvEOPwKWP5pmMOOQfA0EKodQrzDHYB+3k4Qw6iEqBSJvRWlZvrX5gVqCa2a/qtfhuW/taiscC75y0xV57WrabIg6T5l4/1VL56BvJADImUvQaFEfiDmnTYbN6v1aJJaGCGBOzqYK1u/vi9CLBf0250hwjRJpV1fPO93NlYvJnpCHgqxbRC9U3Y0xkeU=
